MySite/urls.py
from django.contrib import admin
from django.urls import path, include

from MySite.settings import DEBUG, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manga_app.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

templates/inc/_navbar.html
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="#" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <img src="https://upload.wikimedia.org/wikipedia/en/7/7f/Manga_Entertainment.svg"
                 width="40" height="32">
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Главная</a></li>
            {% if is_admin %}
            <li><a href="{% url 'addchapter' %}" class="nav-link px-2 link-dark">Добавить главу</a></li>
            <li><a href="{% url 'addmanga' %}" class="nav-link px-2 link-dark">Добавить мангу</a></li>
            {% endif %}
        </ul>

        <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
                <ul class="nav col-12 col-md-auto mb-2 justify-content-end mb-md-0">
                    <li><a href="{% url 'users:profile' %}" class="nav-link px-2 link-dark">{{ user.username }}</a></li>
                    <li><a href="{% url 'users:logout' %}" class="nav-link px-2 link-dark">Выйти</a></li>
                </ul>
            {% else %}
                <button type="button" class="btn btn-outline-primary me-2"
                        onclick="window.location.href='{% url 'users:login' %}';">Войти
                </button>
                <button type="button" class="btn btn-primary"
                        onclick="window.location.href='{% url 'users:register' %}';">Зарегистрироваться
                </button>
            {% endif %}
        </div>
    </header>
</div>